export default {
    day: "Monday",
    program: [
        {
            hour:"00:00",
            content:"Glazba"
        },
        {
            hour:"03:00",
            content:"Domaća glazba"
        },
        {
            hour:"04:00",
            content:"Glazba"
        },
        {
            hour:"07:00",
            content:"Vijesti"
        },
        {
            hour:"08:00",
            content:"Vijesti"
        },
        {
            hour:"09:00",
            content:"Vijesti"
        },
        {
            hour:"10:00",
            content:"Vijesti"
        },
        {
            hour:"11:00",
            content:"Vijesti"
        },
        {
            hour:"11:30",
            content:"Nula41"
        },
        {
            hour:"12:00",
            content:"Vijesti"
        },
        {
            hour:"13:00",
            content:"Katedra"
        },
        {
            hour:"14:00",
            content:"Vijesti"
        },
        {
            hour:"15:00",
            content:"Vijesti"
        },
        {
            hour:"16:00",
            content:"Vijesti"
        },
        {
            hour:"17:00",
            content:"Selo"
        },
        {
            hour:"18:00",
            content:"Vijesti dana"
        },
        {
            hour:"20:00",
            content:"Radio aktivitet"
        },
    ]
}